# Generated by Django 2.1.7 on 2019-11-16 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tick', models.CharField(max_length=120)),
                ('nombre', models.CharField(blank=True, max_length=120, null=True)),
                ('industria', models.CharField(blank=True, max_length=120, null=True)),
                ('sector', models.CharField(blank=True, max_length=120, null=True)),
                ('subsector', models.CharField(blank=True, max_length=120, null=True)),
                ('pais', models.CharField(blank=True, max_length=120, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='all_products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
