# Generated by Django 2.1.7 on 2019-04-01 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tick', models.CharField(max_length=120)),
                ('nombre', models.CharField(max_length=120)),
                ('industria', models.CharField(max_length=120)),
                ('sector', models.CharField(max_length=120)),
                ('subsector', models.CharField(max_length=120)),
                ('pais', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
