# Generated by Django 2.1.7 on 2019-04-01 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acciones', '0002_auto_20190401_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accion',
            name='industria',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='accion',
            name='nombre',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='accion',
            name='pais',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='accion',
            name='sector',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='accion',
            name='subsector',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
