# Generated by Django 2.1.7 on 2019-04-12 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acciones', '0003_auto_20190401_1934'),
    ]

    operations = [
        migrations.CreateModel(
            name='all_products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
